const coffeeShops = [
  {
    id: "shop-01",
    name: "Anomali Coffee Senopati",
    tagline: "Kurator Kopi Asli Nusantara & Suasana Hangat",
    area: "Selatan",
    priceRange: "$$",
    priceNumeric: 35000,
    priceDetails: "Rp 28.000 - Rp 65.000",
    rating: 4.7,
    reviewCount: 1420,
    shortAddress: "Jl. Senopati No. 19, Kebayoran Baru",
    fullAddress: "Jl. Senopati No.19, RT.6/RW.3, Senayan, Kec. Kby. Baru, Kota Jakarta Selatan, DKI Jakarta 12190",
    image: "https://images.unsplash.com/photo-1554118811-1e0d58224f24?auto=format&fit=crop&w=800&q=80",
    mapsUrl: "https://maps.google.com/?q=Anomali+Coffee+Senopati",
    facilities: ["Wi-Fi Kencang", "AC Dingin", "Banyak Stopkontak", "Area Outdoor", "Musala", "Parkir Mobil"],
    openHours: "07:00 - 22:00",
    menuHighlights: ["Kopi Susu Senopati", "Manual Brew Aceh Gayo", "Croissant Almond", "Avocado Coffee"],
    isPopular: true
  },
  {
    id: "shop-02",
    name: "Giyanti Coffee Roastery",
    tagline: "Surga Pecinta Artisan Coffee & Nuansa Vintage Tropis",
    area: "Pusat",
    priceRange: "$$$",
    priceNumeric: 50000,
    priceDetails: "Rp 45.000 - Rp 95.000",
    rating: 4.8,
    reviewCount: 2150,
    shortAddress: "Jl. Surabaya No. 20, Menteng",
    fullAddress: "Jl. Surabaya No.20, RT.15/RW.5, Menteng, Kec. Menteng, Kota Jakarta Pusat, DKI Jakarta 10310",
    image: "https://images.unsplash.com/photo-1501339847302-ac426a4a7cbb?auto=format&fit=crop&w=800&q=80",
    mapsUrl: "https://maps.google.com/?q=Giyanti+Coffee+Roastery+Menteng",
    facilities: ["Wi-Fi Kencang", "AC Dingin", "Taman Tropis", "Area Smoker", "Pet Friendly"],
    openHours: "08:30 - 17:30",
    menuHighlights: ["Toraja Sapan Single Origin", "Flat White Giyanti", "Lamington Cake", "Apple Pie"],
    isPopular: true
  },
  {
    id: "shop-03",
    name: "Kopi Tuku Cipete",
    tagline: "Pelopor Kopi Susu Tetangga yang Selalu Dirindukan",
    area: "Selatan",
    priceRange: "$",
    priceNumeric: 20000,
    priceDetails: "Rp 18.000 - Rp 38.000",
    rating: 4.9,
    reviewCount: 3890,
    shortAddress: "Jl. Cipete Raya No. 7, Cilandak",
    fullAddress: "Jl. Cipete Raya No.7, RT.6/RW.3, Cipete Sel., Kec. Cilandak, Kota Jakarta Selatan, DKI Jakarta 12410",
    image: "https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?auto=format&fit=crop&w=800&q=80",
    mapsUrl: "https://maps.google.com/?q=Toko+Kopi+Tuku+Cipete",
    facilities: ["Stopkontak", "Grab & Go Seating", "Area Parkir Motor", "Outdoor Bench"],
    openHours: "07:00 - 21:00",
    menuHighlights: ["Es Kopi Susu Tetangga", "Donat Kampung", "Bolu Cokelat", "Cold Brew Tetangga"],
    isPopular: true
  },
  {
    id: "shop-04",
    name: "Tanamera Coffee Thamrin",
    tagline: "Specialty Coffee Merah Ikonik Kualitas Dunia",
    area: "Pusat",
    priceRange: "$$",
    priceNumeric: 40000,
    priceDetails: "Rp 35.000 - Rp 75.000",
    rating: 4.6,
    reviewCount: 980,
    shortAddress: "Thamrin City Office Park, Tanah Abang",
    fullAddress: "Thamrin City Office Park Blok AA 07, Kebon Melati, Tanah Abang, Jakarta Pusat 10230",
    image: "https://images.unsplash.com/photo-1521017432531-fbd92d768814?auto=format&fit=crop&w=800&q=80",
    mapsUrl: "https://maps.google.com/?q=Tanamera+Coffee+Thamrin+City",
    facilities: ["Wi-Fi Kencang", "AC Dingin", "Banyak Stopkontak", "Meeting Spot", "Musala Terdekat"],
    openHours: "07:00 - 20:00",
    menuHighlights: ["Red Latte", "Cold Brew Bottle", "Espresso Blend", "Beef Pastrami Croissant"],
    isPopular: false
  },
  {
    id: "shop-05",
    name: "Kopi Kalyan Wijaya",
    tagline: "Tempat Work From Cafe Ternyaman dengan Sentuhan Arsitektur Modern",
    area: "Selatan",
    priceRange: "$$",
    priceNumeric: 38000,
    priceDetails: "Rp 32.000 - Rp 70.000",
    rating: 4.7,
    reviewCount: 1670,
    shortAddress: "Jl. Wijaya IX No. 23, Kebayoran Baru",
    fullAddress: "Jl. Wijaya IX No.23, RT.1/RW.5, Melawai, Kec. Kby. Baru, Kota Jakarta Selatan, DKI Jakarta 12160",
    image: "https://images.unsplash.com/photo-1509042239860-f550ce710b93?auto=format&fit=crop&w=800&q=80",
    mapsUrl: "https://maps.google.com/?q=Kopi+Kalyan+Wijaya",
    facilities: ["Wi-Fi Kencang", "AC Dingin", "Stopkontak Tiap Meja", "Area Outdoor", "Musala", "Parkir Valet"],
    openHours: "06:30 - 22:00",
    menuHighlights: ["Kopi Kalyan Signature", "Chai Latte", "Kalyan Fried Rice", "Banana Bread"],
    isPopular: true
  },
  {
    id: "shop-06",
    name: "Koultoura Coffee Puri",
    tagline: "Desain Estetik Minimalis & Specialty Coffee Pilihan",
    area: "Barat",
    priceRange: "$$",
    priceNumeric: 38000,
    priceDetails: "Rp 30.000 - Rp 80.000",
    rating: 4.6,
    reviewCount: 820,
    shortAddress: "Jl. Surya Mandala I No. 9, Puri Kembangan",
    fullAddress: "Jl. Surya Mandala I No. 9, Kedoya Sel., Kec. Kb. Jeruk, Kota Jakarta Barat, DKI Jakarta 11520",
    image: "https://images.unsplash.com/photo-1442512595331-e89e73853f31?auto=format&fit=crop&w=800&q=80",
    mapsUrl: "https://maps.google.com/?q=Koultoura+Coffee+Puri",
    facilities: ["Wi-Fi Kencang", "AC Dingin", "Area Estetik", "Stopkontak", "Parkir Mobil"],
    openHours: "08:00 - 21:00",
    menuHighlights: ["Dirty Matcha Latte", "Piccolo Latte", "Truffle Fries", "Brioche Toast"],
    isPopular: false
  },
  {
    id: "shop-07",
    name: "Ombe Kofie Pluit",
    tagline: "Hangat, Personal, dan Secangkir Kopi Penuh Karakter",
    area: "Utara",
    priceRange: "$$",
    priceNumeric: 42000,
    priceDetails: "Rp 35.000 - Rp 85.000",
    rating: 4.8,
    reviewCount: 1120,
    shortAddress: "Jl. Pluit Sakti No. 117, Pluit",
    fullAddress: "Jl. Pluit Sakti No.117, RT.1/RW.6, Pluit, Kec. Penjaringan, Kota Jakarta Utara, DKI Jakarta 14450",
    image: "https://images.unsplash.com/photo-1447933601403-0c6688de566e?auto=format&fit=crop&w=800&q=80",
    mapsUrl: "https://maps.google.com/?q=Ombe+Kofie+Pluit",
    facilities: ["Wi-Fi Kencang", "AC Dingin", "Barista Bar", "Cozy Corner", "Stopkontak"],
    openHours: "07:30 - 19:00",
    menuHighlights: ["Thunderbolt Cold Brew", "Hanami Latte", "Pork/Beef Chop Rice", "Regular White"],
    isPopular: true
  },
  {
    id: "shop-08",
    name: "Titik Temu Coffee SCBD",
    tagline: "Titik Bertemu di Tengah Gemerlap Ibukota",
    area: "Selatan",
    priceRange: "$$$",
    priceNumeric: 55000,
    priceDetails: "Rp 45.000 - Rp 110.000",
    rating: 4.7,
    reviewCount: 1540,
    shortAddress: "ASHTA District 8, SCBD",
    fullAddress: "ASHTA District 8 UG Floor, Senayan, Kebayoran Baru, Jakarta Selatan 12190",
    image: "https://images.unsplash.com/photo-1559925393-8be0ec4767c8?auto=format&fit=crop&w=800&q=80",
    mapsUrl: "https://maps.google.com/?q=Titik+Temu+Coffee+ASHTA+SCBD",
    facilities: ["Wi-Fi Super Cepat", "AC Dingin", "Semi Outdoor Terrace", "Banyak Stopkontak", "Musala Mall"],
    openHours: "08:00 - 22:00",
    menuHighlights: ["Iced Pandan Latte", "Filter Geisha Coffee", "Avocado Toast", "Temu Truffle Pasta"],
    isPopular: true
  },
  {
    id: "shop-09",
    name: "Kopi Kenangan Heritage Senayan",
    tagline: "Eksplorasi Varian Biji Kopi Nusantara dengan Suasana Premium",
    area: "Pusat",
    priceRange: "$$",
    priceNumeric: 32000,
    priceDetails: "Rp 24.000 - Rp 65.000",
    rating: 4.5,
    reviewCount: 760,
    shortAddress: "Senayan City Mall GF, Jl. Asia Afrika",
    fullAddress: "Senayan City Ground Floor, Jl. Asia Afrika No.19, Gelora, Tanah Abang, Jakarta Pusat 10270",
    image: "https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?auto=format&fit=crop&w=800&q=80",
    mapsUrl: "https://maps.google.com/?q=Kopi+Kenangan+Heritage+Senayan+City",
    facilities: ["Wi-Fi Kencang", "AC Dingin", "Sofa Luas", "Banyak Stopkontak", "Musala Mall"],
    openHours: "10:00 - 22:00",
    menuHighlights: ["Kenangan Mantan Reserve", "Avocado Dutch Chocolate", "Croffle Cheese", "Single Origin Flores"],
    isPopular: false
  },
  {
    id: "shop-10",
    name: "Kedai Kopi Menanti Rawamangun",
    tagline: "Kedai Kopi Santai Ramah Kantong Mahasiswa",
    area: "Timur",
    priceRange: "$",
    priceNumeric: 18000,
    priceDetails: "Rp 15.000 - Rp 35.000",
    rating: 4.6,
    reviewCount: 640,
    shortAddress: "Jl. Balai Pustaka Timur No. 14, Rawamangun",
    fullAddress: "Jl. Balai Pustaka Timur No.14, RT.4/RW.9, Rawamangun, Kec. Pulo Gadung, Kota Jakarta Timur, DKI Jakarta 13220",
    image: "https://images.unsplash.com/photo-1497636577773-f1231844b336?auto=format&fit=crop&w=800&q=80",
    mapsUrl: "https://maps.google.com/?q=Kedai+Kopi+Rawamangun",
    facilities: ["Wi-Fi Gratis", "Banyak Colokan", "Area Outdoor Adem", "Musala", "Parkir Luas"],
    openHours: "09:00 - 23:00",
    menuHighlights: ["Kopi Susu Aren Menanti", "Manual Brew Robusta Lampung", "Roti Bakar Cokelat Keju", "Indomie Katsu"],
    isPopular: false
  },
  {
    id: "shop-11",
    name: "Bukan Kopi Biasa Kelapa Gading",
    tagline: "Tempat Diskusi Hangat dan Seduhan V60 Terkurasi",
    area: "Utara",
    priceRange: "$$",
    priceNumeric: 30000,
    priceDetails: "Rp 22.000 - Rp 55.000",
    rating: 4.7,
    reviewCount: 890,
    shortAddress: "Boulevard Raya Blok QA 1 No. 8, Kelapa Gading",
    fullAddress: "Jl. Boulevard Raya Blok QA 1 No.8, Kelapa Gading Barat, Jakarta Utara 14240",
    image: "https://images.unsplash.com/photo-1461023058943-07fcbe16d735?auto=format&fit=crop&w=800&q=80",
    mapsUrl: "https://maps.google.com/?q=Bukan+Kopi+Biasa+Kelapa+Gading",
    facilities: ["Wi-Fi Kencang", "AC Dingin", "Area Non-Smoker", "Banyak Stopkontak", "Board Games"],
    openHours: "08:00 - 22:00",
    menuHighlights: ["Filter Coffee Bali Kintamani", "Iced Salted Caramel", "Choco Fudge Tart", "Spaghetti Aglio Olio"],
    isPopular: false
  },
  {
    id: "shop-12",
    name: "Ruang Seduh Duren Sawit",
    tagline: "Konsep Open Bar & Edukasi Kopi untuk Semua",
    area: "Timur",
    priceRange: "$$",
    priceNumeric: 28000,
    priceDetails: "Rp 20.000 - Rp 48.000",
    rating: 4.8,
    reviewCount: 520,
    shortAddress: "Jl. Kolonel Sugiono No. 45, Duren Sawit",
    fullAddress: "Jl. Kolonel Sugiono No.45, RT.2/RW.2, Duren Sawit, Kec. Duren Sawit, Kota Jakarta Timur, DKI Jakarta 13440",
    image: "https://images.unsplash.com/photo-1498804103079-a6351b050096?auto=format&fit=crop&w=800&q=80",
    mapsUrl: "https://maps.google.com/?q=Ruang+Seduh+Duren+Sawit",
    facilities: ["Wi-Fi Kencang", "AC Dingin", "Bar Experience", "Stopkontak", "Area Parkir"],
    openHours: "10:00 - 22:00",
    menuHighlights: ["Espresso Tonic", "Pour Over West Java", "Earl Grey Chiffon Cake", "Matcha Cream"],
    isPopular: false
  }
];
